name: reflective
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/reflection
version: 0.0.1
description: Box Data Store
dependencies:
dev_dependencies:
  unittest: any
