name: reflective
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/reflection
version: 0.0.19
description: A fluent reflection API
dependencies:
dev_dependencies:
  unittest: any
  collection: any
