name: reflective
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/reflection
version: 0.0.27
description: A fluent reflection API
dependencies:
  yaml: ">=2.1.0 <3.0.0"
dev_dependencies:
  test: any
  collection: any
